services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    image: traefik:v3.0.1
    container_name: prod-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mnt/prod/letsencrypt:/letsencrypt
    profiles:
      - jupyterhub
    networks:
      - bridge

  jupyterhub:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyterhub.rule=Host(`jupyter.${DOMAIN}`)"
      - "traefik.http.routers.jupyterhub.entrypoints=websecure"
      - "traefik.http.routers.jupyterhub.tls.certresolver=myresolver"
      - "traefik.http.services.jupyterhub.loadbalancer.server.port=8000"
    ports: !reset []


  erigon:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erigon.rule=Host(`erigon.${DOMAIN}`)"
      - "traefik.http.routers.erigon.entrypoints=websecure"
      - "traefik.http.routers.erigon.tls.certresolver=myresolver"
      - "traefik.http.services.erigon.loadbalancer.server.port=8545"
    command: >
      --chain=mainnet
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=eth,net,web3
      --http.corsdomain=*
      --http.vhosts=*
      --maxpeers=100
      --datadir=/erigon
      --ws
      --ws.compression
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --torrent.upload.rate=512mb
      --torrent.download.rate=512mb
      --log.console.verbosity=debug
      --metrics
    ports: !reset []

  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    ports: !reset []